### ISSUE TITLE
Feature Request: Naively Alert against Custom Events / Send Notification from Custom Event 

### ISSUE THREAD

**Issue by darrenway** [draios/sysdigcloud-kubernetes#11]
https://github.com/draios/sysdig/issues/795#issue-216454059

I raised this feature request on the Sysdig Opensource

@payalc5 responded with this https://github.com/draios/sysdig/issues/795#issuecomment-289652359 stating this is in the process of being implemented and asked if we would like a demo. 

@luca3m closed the other issue.

I am re-raising the issue here to track this

**Comment by darrenway** [comment]
Issue Text:
We have set up alerting against our application and send these to a slack channel,

I am interested to know if we can set up an Alert for if custom event from kube/docker/falco occurs, or send a notification to a slack channel if a given custom even occurs,

Essentially, I want an alert to fire, if we receive a 'Container Killed' custom event from docker, but as this is not a metric known to sysdig, we cannot alert against this. We are unable to involve sysdigbot in our instance

This seems like a Feature Request to me, if it's already possible i'm more than happy to be proved wrong!

**Comment by markyjackson-taulia** [comment]
@darrenway 
I am one of the new maintainers of the repo and want to make sure items got addressed. I looked in to this and you can in fact so this. I have attached a screen shot:
<img width="1535" alt="screen shot 2018-05-24 at 15 34 20" src="https://user-images.githubusercontent.com/16655670/40489174-62e6c922-5f1d-11e8-92bd-1defc1ed4e04.png">
Hopefully it is viewable. I will leave this open a few more days so we can make sure you are good.
Thanks kindly :-)
