### ISSUE TITLE
Healthcheck For Cassandra

### ISSUE THREAD

**Issue by gileshinchcliff** [draios/sysdigcloud-kubernetes#5]
Hi Guys,

As we're using your cassandra image to run our sysdigcloud k8s stack, do you have any suggestions about healthchecking it? Is there a Dockerfile for cassandra that would write PR's for to extend?
Cheers.

Giles

**Comment by ltagliamonte** [comment]
Hello @gileshinchcliff unfortunately the cassandra docker file is not public.
For what I'm aware of, latest kubernetes stable do not currently uses the latest docker Healthcheck instruction/data to manage pod healthiness; what I can definitely suggest is to add to the cassandra deployment definition a k8s liveness probe that can be of type exec or TCP.
What do you think about?
