### ISSUE TITLE
Is the second redis.endpoint entry missing here?

### ISSUE THREAD

**Issue by bennythejudge** [draios/sysdigcloud-kubernetes#54]
https://github.com/draios/sysdigcloud-kubernetes/blob/8e7a7af68e97ba2c0c6222e4b15fa7870e62860e/sysdigcloud/config.yaml#L42

I am in the combined HA branch and the config.yaml does not have the second `redis.endpoint` entry.
Is that the way it is now?

**Comment by markyjackson-taulia** [comment]
@bennythejudge  yes. The sentinel now controls leader election
