### ISSUE TITLE
get_support_bundle.sh stops if any pod is "completed"

### ISSUE THREAD

**Issue by curionim** [draios/sysdigcloud-kubernetes#75]
Tried to run the script and it started looping through the pods in the given namespace with output:
"Getting support logs for ..."
But then it failed with error:
"error: cannot exec into a container in a completed pod; current phase is Succeeded"

Maybe there could be a check on the pod status before attempting to "exec" into it, or catch the exception and continue.

**Comment by markyjackson-taulia** [comment]
Fix to the issue is not in the dev branch
